name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    env: 
      API_KEY: ${{ MICROCMS_API_KEY }}
    steps:
    - uses: actions/checkout@v2


    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'


    - name: install
      run: yarn


    - name: build
      run: yarn build


    - name: export files
      run: yarn export


    - name: add nojekyll
      run: touch ./out/.nojekyll


    - name: deploy pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        publish_dir: ./out
